// Smart Retry Scenarios - 4 specific retry strategies

export const retryMechanisms = [
  { id: 'stepUp', name: '3DS Step-up', description: 'Add 3D Secure authentication' },
  { id: 'credential', name: 'Switch Creds', description: 'Switch from token to clear PAN' },
  { id: 'networkSwitch', name: 'Switch Network', description: 'Switch between debit/signature networks' },
  { id: 'cascade', name: 'Cascade', description: 'Cascade to alternate processor' },
];

export const retryScenarios = [
  {
    id: 'stepup_cascade',
    name: 'Step-up & Cascade',
    description: '3DS authentication then cascade to alternate PSP',
    detailedDescription: 'PSP1 detects suspected fraud. System performs 3DS frictionless step-up with independent provider. PSP1 still declines. System cascades to PSP2 with 3DS payload and succeeds.',
    mechanisms: ['stepUp', 'cascade'],
    attempts: [
      {
        id: 1,
        psp: 'PSP1',
        payload: 'Standard',
        status: 'declined',
        errorCode: '05',
        errorMessage: 'Suspected fraud',
        strategy: '3DS Step-up',
      },
      {
        id: 2,
        psp: 'PSP1',
        payload: 'With 3DS frictionless',
        status: 'declined',
        errorCode: '51',
        errorMessage: 'Generic decline',
        strategy: 'Cascade',
      },
      {
        id: 3,
        psp: 'PSP2',
        payload: 'With 3DS payload',
        status: 'approved',
        authCode: '883746',
        network: 'Visa',
        strategy: null,
      },
    ],
  },
  {
    id: 'creds_cascade',
    name: 'Switch Creds & Cascade',
    description: 'Network token to clear PAN then cascade',
    detailedDescription: 'PSP1 with network token fails. System switches to raw PAN and retries with PSP1. PSP1 still declines. System cascades to PSP2 with raw PAN and succeeds.',
    mechanisms: ['credential', 'cascade'],
    attempts: [
      {
        id: 1,
        psp: 'PSP1',
        payload: 'Network token',
        status: 'declined',
        errorCode: '82',
        errorMessage: 'Invalid cryptogram',
        strategy: 'Switch Creds',
      },
      {
        id: 2,
        psp: 'PSP1',
        payload: 'Raw PAN',
        status: 'declined',
        errorCode: '65',
        errorMessage: 'Do not honor',
        strategy: 'Cascade',
      },
      {
        id: 3,
        psp: 'PSP2',
        payload: 'Raw PAN',
        status: 'approved',
        authCode: '492817',
        network: 'Mastercard',
        strategy: null,
      },
    ],
  },
  {
    id: 'network_cascade',
    name: 'Switch Network & Cascade',
    description: 'Local debit to global network then cascade',
    detailedDescription: 'PSP1 with local debit rail fails. System switches to global network (Visa/Mastercard) and retries with PSP1. PSP1 still declines. System cascades to PSP2 with global network and succeeds.',
    mechanisms: ['networkSwitch', 'cascade'],
    attempts: [
      {
        id: 1,
        psp: 'PSP1',
        payload: 'Local debit rail',
        status: 'declined',
        errorCode: '57',
        errorMessage: 'Transaction not permitted',
        strategy: 'Switch Network',
      },
      {
        id: 2,
        psp: 'PSP1',
        payload: 'Global network',
        status: 'declined',
        errorCode: '51',
        errorMessage: 'Generic decline',
        strategy: 'Cascade',
      },
      {
        id: 3,
        psp: 'PSP2',
        payload: 'Global network',
        status: 'approved',
        authCode: '756341',
        network: 'Visa',
        strategy: null,
      },
    ],
  },
  {
    id: 'quick_cascade',
    name: 'Quick Cascade',
    description: 'Cascade through PSP1, PSP2, PSP3',
    detailedDescription: 'PSP1 with raw PAN fails. System cascades to PSP2 which also fails. System cascades to PSP3 and succeeds. Payload is enhanced for each PSP to ensure compatibility.',
    mechanisms: ['cascade'],
    attempts: [
      {
        id: 1,
        psp: 'PSP1',
        payload: 'Raw PAN',
        status: 'declined',
        errorCode: '96',
        errorMessage: 'Processing error',
        strategy: 'Cascade',
      },
      {
        id: 2,
        psp: 'PSP2',
        payload: 'Raw PAN',
        status: 'declined',
        errorCode: '14',
        errorMessage: 'Invalid card',
        strategy: 'Cascade',
      },
      {
        id: 3,
        psp: 'PSP3',
        payload: 'Raw PAN',
        status: 'approved',
        authCode: '445566',
        network: 'Visa',
        strategy: null,
      },
    ],
  },
];

export default retryScenarios;
