apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hyperswitch-demo

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - nginx-configmap.yaml
  - server-deployment.yaml
  - server-hpa.yaml
  - client-deployment.yaml
  - client-hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: hyperswitch-demo
  app.kubernetes.io/part-of: hyperswitch-demo
