apiVersion: v1
kind: Secret
metadata:
  name: hyperswitch-secrets
  namespace: hyperswitch-demo
type: Opaque
stringData:
  HYPERSWITCH_PUBLISHABLE_KEY: "pk_snd_4bf1b4cb016b4b979ce210e011cafa4a"
  HYPERSWITCH_SECRET_KEY: "snd_K4Dsbnx8Or6RCXMLbap182TtDCPLqwrU3eZgPjLuoYmmcvDn4ZVLGI1cwRBBL7es"
  EMBED_PROFILE_ID: "pro_RFrY15EdR9n22IBbrCoE"
  PROFILE_ID: "pro_N6tqlbSOXjTN42Go3dgL"
  CUSTOMER_ID: "cus_demo_001"
  ADYEN_API_KEY: "AQEqhmfxKYLIYxVHw0m/n3Q5qf3VYp5eHZJTfEB5RBielkT6RxiSh36AXPkJEMFdWw2+5HzctViMSCJMYAc=-/DbaImPd8JrXvNtw2eXUH0RNsBOeqX4U1E0V70huDg4=-pz<)WaVBz2MuF3gP"
  ADYEN_MERCHANT_ACCOUNT: "JuspayDEECOM"
  MERCHANT_CONNECTOR_ID: "mca_zaNgRbqSDoFFEyDDamoj"
